apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: procosys-preservation-api
spec:
  environments:
  - name: dev
  - name: test
  - name: prod

  components:
  # ---------
  # Backend
  #---------- 

  - name: backend
    image: procosys.azurecr.io/preservation/api:{imageTagName}
    ports:
    - name: http
      port: 5000
    publicPort: http
    secrets:
    - CONNECTIONSTRINGS__APPCONFIG
    environmentConfig:
    # Development environment
    - environment: dev
      identity:
        azure:
          clientId: 67b2f053-30bf-4ffc-9206-ef57f631efcb
      imageTagName: latest
      variables:
        Application__AppConfigurationUrl: https://pcs-pres-non-prod-config.azconfig.io
        Application__ObjectId: e4a7f1b1-da31-40ac-9089-d00afc2f1fa7
        Application__UseAzureAppConfiguration: 'true'
        AzureAd__ClientId: 67b2f053-30bf-4ffc-9206-ef57f631efcb
        AzureAd__ClientCredentials__0__SourceType: SignedAssertionFilePath
        ASPNETCORE_ENVIRONMENT: 'Development'
        LEADERELECTOR_SERVICE: http://leader-elector:3003
        MainApi__BaseAddress: 'https://pcs-main-api-dev.azurewebsites.net/api/'
        MainApi__MainApiScope: 'api://dd38f169-bccf-4d0e-a4ad-d830893cfa75/.default'
        ServiceBus__Enable: 'true'
        Swagger__Audience: 'api://67b2f053-30bf-4ffc-9206-ef57f631efcb'
        Swagger__ClientId: '97505617-302f-409a-a37e-7ca859b5b56c'
        UseAzureAppConfiguration: 'true' #TODO 1064: Remove this once all environments are using Application__UseAzureAppConfiguration
      monitoring: false
      resources:
        requests:
          memory: '256Mi'
          cpu: '100m'
        limits:
          memory: '256Mi'
          cpu: '250m'
    # Test environment
    - environment: test
      identity:
        azure:
          clientId: f23bcde6-d6a4-42d5-94fa-96b184968cf7
      variables:
        Application__AppConfigurationUrl: https://pcs-pres-non-prod-config.azconfig.io
        Application__ObjectId: a0ff0648-043e-49fd-ac69-5a8d9af932c6
        Application__UseAzureAppConfiguration: 'true'
        AzureAd__ClientId: f23bcde6-d6a4-42d5-94fa-96b184968cf7
        AzureAd__ClientCredentials__0__SourceType: SignedAssertionFilePath
        ASPNETCORE_ENVIRONMENT: 'Test'
        LEADERELECTOR_SERVICE: http://leader-elector:3003
        MainApi__BaseAddress: 'https://procosyswebapitest.equinor.com/api/'
        MainApi__MainApiScope: 'api://2d0ed80f-3013-422d-b8bd-2b8ac70b2ce1/.default'
        ServiceBus__Enable: 'true'
        Swagger__Audience: 'api://f23bcde6-d6a4-42d5-94fa-96b184968cf7'
        Swagger__ClientId: '3c391792-dbea-446e-bb2c-a7bda2fe40dd'
        UseAzureAppConfiguration: 'true' #TODO 1064: Remove this once all environments are using Application__UseAzureAppConfiguration
      monitoring: false
      replicas: 2
      resources:
        requests:
          memory: '350Mi' #TODO 1064: Memory usage is at 99% usage when set to 256. If it also goes to 99% with 350, we have a leak. 
          cpu: '100m'
        limits:
          memory: '350Mi' #TODO 1064: Memory usage is at 99% usage when set to 256. If it also goes to 99% with 350, we have a leak. 
          cpu: '250m'
    # Prod environment
    - environment: prod
      identity:
        azure:
          clientId: 1eb50c54-e897-4216-93d0-6ca86b0cf681
      variables:
        Application__AppConfigurationUrl: https://pcs-pres-prod-config.azconfig.io
        Application__ObjectId: 'd28c8b2a-2a2a-4fc1-97c6-49c3e601a3e3'
        Application__UseAzureAppConfiguration: 'true'
        AzureAd__ClientId: 1eb50c54-e897-4216-93d0-6ca86b0cf681
        AzureAd__ClientCredentials__0__SourceType: SignedAssertionFilePath
        ASPNETCORE_ENVIRONMENT: 'Prod'
        LEADERELECTOR_SERVICE: http://leader-elector:3003
        MainApi__BaseAddress: 'https://procosyswebapi.equinor.com/api/'
        MainApi__MainApiScope: 'api://47641c40-0135-459b-8ab4-459e68dc8d08/.default'
        ServiceBus__Enable: 'true'
        Swagger__Audience: 'api://1eb50c54-e897-4216-93d0-6ca86b0cf681'
        Swagger__ClientId: '42f01d41-df15-426f-8332-bf58d7274964'
        UseAzureAppConfiguration: 'true' #TODO 1064: Remove this once all environments are using Application__UseAzureAppConfiguration
      monitoring: false
      replicas: 3
      resources:
        requests:
          memory: '750Mi'
          cpu: '200m'
        limits:
          memory: '750Mi'
          cpu: '500m'

  #--------------------
  # LeaderElector 
  #--------------------
  - name: leader-elector
    image: procosys.azurecr.io/leader-elector:{imageTagName}
    ports:
    - name: http
      port: 3003
    environmentConfig:
    # Development environment
    - environment: dev
      imageTagName: latest
      variables:
        LEASE_TIME: 5
      monitoring: false
      replicas: 1
      resources:
        requests:
          memory: '128Mi'
          cpu: '100m'
        limits:
          memory: '128Mi'
          cpu: '100m'
    # Test environment
    - environment: test
      variables:
        LEASE_TIME: 5
      monitoring: false
      replicas: 1
      resources:
        requests:
          memory: '128Mi'
          cpu: '100m'
        limits:
          memory: '128Mi'
          cpu: '100m'
    # Prod environment
    - environment: prod
      variables:
         LEASE_TIME: 5
      replicas: 1
      resources:
        requests:
          memory: '128Mi'
          cpu: '100m'
        limits:
          memory: '128Mi'
          cpu: '100m'
      monitoring: false
  #--------------------------------
  # External docker image registry
  #--------------------------------
  privateImageHubs:
    procosys.azurecr.io:
      username: 9d3898e4-730f-4fb5-8ddf-a5de51537896
      email: arbje@equinor.com
