trigger:
  branches:
    include:
      - build-test

resources:
  repositories:
  - repository: self
  - repository: templates
    type: github
    name: equinor/procosys-preservation-infra
    endpoint: 'Preservation - Frontend'

# Global variables for the pipeline
variables:
 - template: templates/variables/preservation-variables.yml@templates
 - template: templates/variables/procosys-global-variables.yml@templates

 - name: 'repositoryName'
   value: 'preservation/api'

stages:
# common stage. Docker build, tag and push
- stage: common
  displayName: 'Common'
  variables:
    envName: 'common'
    envRg: '${{ variables.envRgName }}'
    containerRegistry: '${{ variables.containerRegistryName }}'
    envGroupName: '$(globalPrefix)-$(fullAppName)-${{ variables.envName }}'
    dockerRegistryServiceConnection: '$(dockerRegistryServiceConnectionName)'
    dockerfilePath: '$(Build.SourcesDirectory)/src/Equinor.Procosys.Preservation.WebApi/Dockerfile'

  jobs:
  - template: /templates/pipelines/dockerbuild.yml@templates
    parameters:
      deploymentName: 'docker_build_push'
      dependsOn: ''
      env: 'pcs-${{ variables.envName }}'
      envGroup: '${{ variables.envGroupName }}'
      dockerfilePath: ${{ variables.dockerfilePath }}
      buildContext: '$(Build.SourcesDirectory)/src'
      repository: ${{ variables.repositoryName }}
      dockerRegistryServiceConnection: $(dockerRegistryServiceConnectionName)

# Dev deploy stage
- stage: dev
  displayName: 'Dev'
  variables:
    envName: 'dev'
    envRg: '${{ variables.envRgName }}'
    envGroupName: '$(globalPrefix)-$(fullAppName)-${{ variables.envName }}'
    serviceConnection: '${{ variables.nonProdServiceConnection }}'
    appServicePlan: '${{ variables.nonProdappServicePlanName }}'
    containerRegistry: '${{ variables.containerRegistryName }}' 

  jobs:
  - template: /templates/pipelines/webapprelease.yml@templates
    parameters:
      dependsOn: ''
      deploymentName: 'publish_container_to_webapp'
      serviceConnection: '${{ variables.serviceConnection }}'
      webApp: '${{ variables.apiWebAppName }}'
      envGroup: '${{ variables.envGroupName }}'
      envRg: '${{ variables.envRg }}'
      env: '${{ variables.envName }}'
      containerRegistry: '${{ variables.containerRegistry }}'
      repository: ${{ variables.repositoryName }}