name: 🚀🏭 Deploy rollback to prod

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to rollback to (branch, tag or commit SHA)
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      github-environment: prod-rollback
      radix-environment: prod
      deploy-ref: ${{ inputs.ref }}
